# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
maxUnavailable: 0

image:
  repository: hypertrace/gateway-service
  pullPolicy: IfNotPresent
  tagOverride: ""

imagePullSecrets: []

containerPort: 50071
containerAdminPort: 50072
containerPortName: grpc

env: []

service:
  type: ClusterIP
  port: 50071
  adminPort: 50072

nodeLabels: {}

javaOpts: "-XX:InitialRAMPercentage=50.0 -XX:MaxRAMPercentage=75.0"

livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10
readinessProbe:
  initialDelaySeconds: 2
  periodSeconds: 5

resources:
   limits:
     cpu: 1
     memory: 1024Mi
   requests:
     cpu: 150m
     memory: 1024Mi

deploymentLabels:
  app: gateway-service

podLabels:
  app: gateway-service

podAnnotations: {}

deploymentSelectorMatchLabels:
  app: gateway-service

serviceSelectorLabels:
  app: gateway-service

configMap:
  name: gateway-service-config
  data:
    application.conf: |-
      entity.service.config = {
        host = entity-service
      }
      query.service.config = {
        host = query-service
      }
      attributes.service.config = {
        host = attribute-service
      }
logConfig:
  name: gateway-service-log-config
  monitorInterval: 30
  rootLogger:
    level: INFO
  appender:
    rolling:
      enabled: false
