name: Dependency Check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dependency-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Dependency Check
        uses: hypertrace/github-actions/dependency-check@main